const words = [
  {
    id: '5e9f5ee35eb9e72bc21af734',
    group: 1,
    page: 3,
    word: 'chest',
    image: 'files/04_0661.jpg',
    audio: 'files/04_0661.mp3',
    audioMeaning: 'files/04_0661_meaning.mp3',
    audioExample: 'files/04_0661_example.mp3',
    textMeaning: 'The <i>chest</i> is the front part of a body between the neck and stomach.',
    textExample: 'The water in the lake was as high as my <b>chest</b>.',
    transcription: '[tʃest]',
    textExampleTranslate: 'Вода в озере была так же высока, как моя грудь',
    textMeaningTranslate: 'Грудь - это передняя часть тела между шеей и животом',
    wordTranslate: 'грудь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af735',
    group: 1,
    page: 3,
    word: 'confidence',
    image: 'files/04_0662.jpg',
    audio: 'files/04_0662.mp3',
    audioMeaning: 'files/04_0662_meaning.mp3',
    audioExample: 'files/04_0662_example.mp3',
    textMeaning: '<i>Confidence</i> is a feeling of certainty or ability.',
    textExample: 'I have <b>confidence</b> that I did well on the test.',
    transcription: '[kɑ́nfidəns]',
    textExampleTranslate: 'У меня есть уверенность, что я хорошо справился с тестом',
    textMeaningTranslate: 'Уверенность - это чувство уверенности или способности',
    wordTranslate: 'доверие',
  },
  {
    id: '5e9f5ee35eb9e72bc21af736',
    group: 1,
    page: 3,
    word: 'consequence',
    image: 'files/04_0663.jpg',
    audio: 'files/04_0663.mp3',
    audioMeaning: 'files/04_0663_meaning.mp3',
    audioExample: 'files/04_0663_example.mp3',
    textMeaning: 'A <i>consequence</i> is a result of a choice or action.',
    textExample: 'As a <b>consequence</b> of missing my bus, I had to find another way to work.',
    transcription: '[kɑ́nsikwèns]',
    textExampleTranslate: 'Из-за пропавшего автобуса мне пришлось искать другой способ работы',
    textMeaningTranslate: 'Следствие - это результат выбора или действия',
    wordTranslate: 'следствие',
  },
  {
    id: '5e9f5ee35eb9e72bc21af737',
    group: 1,
    page: 3,
    word: 'disaster',
    image: 'files/04_0664.jpg',
    audio: 'files/04_0664.mp3',
    audioMeaning: 'files/04_0664_meaning.mp3',
    audioExample: 'files/04_0664_example.mp3',
    textMeaning: 'A <i>disaster</i> is a really bad thing that happens.',
    textExample: 'When the car crashed, it was a <b>disaster</b>.',
    transcription: '[dizǽstər]',
    textExampleTranslate: 'Когда машина разбилась, это была катастрофа',
    textMeaningTranslate: 'Бедствие - это действительно плохая вещь, которая случается',
    wordTranslate: 'стихийное бедствие',
  },
  {
    id: '5e9f5ee35eb9e72bc21af738',
    group: 1,
    page: 3,
    word: 'disturb',
    image: 'files/04_0665.jpg',
    audio: 'files/04_0665.mp3',
    audioMeaning: 'files/04_0665_meaning.mp3',
    audioExample: 'files/04_0665_example.mp3',
    textMeaning: 'To <i>disturb</i> someone means to upset that person.',
    textExample: 'The loud noise <b>disturbed</b> me while I was working.',
    transcription: '[distə́ːrb]',
    textExampleTranslate: 'Громкий шум беспокоил меня, когда я работал',
    textMeaningTranslate: 'Беспокоить кого-то значит расстроить этого человека',
    wordTranslate: 'беспокоить',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73a',
    group: 1,
    page: 3,
    word: 'impress',
    image: 'files/04_0668.jpg',
    audio: 'files/04_0668.mp3',
    audioMeaning: 'files/04_0668_meaning.mp3',
    audioExample: 'files/04_0668_example.mp3',
    textMeaning: 'To <i>impress</i> someone means to make that person proud or amazed.',
    textExample: 'He was able to <b>impress</b> the girls with his new dance.',
    transcription: '[imprés]',
    textExampleTranslate: 'Он смог впечатлить девушек своим новым танцем',
    textMeaningTranslate: 'Произвести на кого-то впечатление - значит сделать его гордым или удивленным',
    wordTranslate: 'произвести впечатление',
  },
  {
    id: '5e9f5ee35eb9e72bc21af739',
    group: 1,
    page: 3,
    word: 'estimate',
    image: 'files/04_0666.jpg',
    audio: 'files/04_0666.mp3',
    audioMeaning: 'files/04_0666_meaning.mp3',
    audioExample: 'files/04_0666_example.mp3',
    textMeaning: 'To <i>estimate</i> something means to make a guess about it.',
    textExample: 'The boy <b>estimated</b> that he was one meter tall.',
    transcription: '[éstəmèit]',
    textExampleTranslate: 'Мальчик подсчитал, что он был один метр в высоту',
    textMeaningTranslate: 'Оценить что-то значит догадаться об этом',
    wordTranslate: 'оценить',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73b',
    group: 1,
    page: 3,
    word: 'honor',
    image: 'files/04_0667.jpg',
    audio: 'files/04_0667.mp3',
    audioMeaning: 'files/04_0667_meaning.mp3',
    audioExample: 'files/04_0667_example.mp3',
    textMeaning: 'To <i>honor</i> is to show respect for someone or something.',
    textExample: 'Each year we <b>honor</b> those who died fighting for their country.',
    transcription: '[ɑ́nər]',
    textExampleTranslate: 'Каждый год мы чтим тех, кто погиб, сражаясь за свою страну',
    textMeaningTranslate: 'Честь - это проявление уважения к кому-то или чему-либо',
    wordTranslate: 'честь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73c',
    group: 1,
    page: 3,
    word: 'narrow',
    image: 'files/04_0669.jpg',
    audio: 'files/04_0669.mp3',
    audioMeaning: 'files/04_0669_meaning.mp3',
    audioExample: 'files/04_0669_example.mp3',
    textMeaning: 'A <i>narrow</i> object or space is thin, not wide.',
    textExample: 'The bridge is too <b>narrow</b> for a car to drive across it.',
    transcription: '[nǽrou]',
    textExampleTranslate: 'Мост слишком узкий, чтобы по нему могла проехать машина',
    textMeaningTranslate: 'Узкий предмет или пространство тонкое, а не широкое',
    wordTranslate: 'узкий',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73e',
    group: 1,
    page: 3,
    word: 'rough',
    image: 'files/04_0671.jpg',
    audio: 'files/04_0671.mp3',
    audioMeaning: 'files/04_0671_meaning.mp3',
    audioExample: 'files/04_0671_example.mp3',
    textMeaning: 'A <i>rough</i> thing is not even or smooth.',
    textExample: 'The <b>rough</b> ground hurt my feet.',
    transcription: '[rʌf]',
    textExampleTranslate: 'Грубая земля повредила мои ноги',
    textMeaningTranslate: 'Грубая вещь не ровная или гладкая',
    wordTranslate: 'грубый',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73d',
    group: 1,
    page: 3,
    word: 'pale',
    image: 'files/04_0670.jpg',
    audio: 'files/04_0670.mp3',
    audioMeaning: 'files/04_0670_meaning.mp3',
    audioExample: 'files/04_0670_example.mp3',
    textMeaning: '<i>Pale</i> means that a color or thing is not bright.',
    textExample: 'The girl’s skin was very <b>pale</b>.',
    transcription: '[peil]',
    textExampleTranslate: 'Кожа девушки была очень бледной',
    textMeaningTranslate: 'Бледный означает, что цвет или вещь не яркие',
    wordTranslate: 'бледный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af73f',
    group: 1,
    page: 3,
    word: 'satisfy',
    image: 'files/04_0672.jpg',
    audio: 'files/04_0672.mp3',
    audioMeaning: 'files/04_0672_meaning.mp3',
    audioExample: 'files/04_0672_example.mp3',
    textMeaning: 'To <i>satisfy</i> someone means to make that person happy.',
    textExample: 'It will <b>satisfy</b> my teacher if I finish all my homework.',
    transcription: '[sǽtisfài]',
    textExampleTranslate: 'Это удовлетворит моего учителя, если я закончу всю домашнюю работу',
    textMeaningTranslate: 'Удовлетворить кого-то - значит сделать этого человека счастливым',
    wordTranslate: 'удовлетворяют',
  },
  {
    id: '5e9f5ee35eb9e72bc21af740',
    group: 1,
    page: 3,
    word: 'scream',
    image: 'files/04_0673.jpg',
    audio: 'files/04_0673.mp3',
    audioMeaning: 'files/04_0673_meaning.mp3',
    audioExample: 'files/04_0673_example.mp3',
    textMeaning: 'To <i>scream</i> means to make a loud noise with your mouth.',
    textExample: 'The girl saw a spider and <b>screamed</b>.',
    transcription: '[skriːm]',
    textExampleTranslate: 'Девушка увидела паука и закричала',
    textMeaningTranslate: 'Кричать - значит громко шуметь ртом',
    wordTranslate: 'кричать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af741',
    group: 1,
    page: 3,
    word: 'sensitive',
    image: 'files/04_0674.jpg',
    audio: 'files/04_0674.mp3',
    audioMeaning: 'files/04_0674_meaning.mp3',
    audioExample: 'files/04_0674_example.mp3',
    textMeaning: 'A <i>sensitive</i> person or thing is easily hurt.',
    textExample: 'My teeth are <b>sensitive</b> to cold things.',
    transcription: '[sénsətiv]',
    textExampleTranslate: 'Мои зубы чувствительны к холодным вещам',
    textMeaningTranslate: 'Чувствительный человек или вещь легко болят',
    wordTranslate: 'чувствительный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af742',
    group: 1,
    page: 3,
    word: 'shade',
    image: 'files/04_0675.jpg',
    audio: 'files/04_0675.mp3',
    audioMeaning: 'files/04_0675_meaning.mp3',
    audioExample: 'files/04_0675_example.mp3',
    textMeaning: '<i>Shade</i> is a dark area that something makes when it blocks the sun.',
    textExample: 'It was hot outside, so the boy sat in the <b>shade</b> of a tree.',
    transcription: '[ʃeid]',
    textExampleTranslate: 'На улице было жарко, поэтому мальчик сидел в тени дерева',
    textMeaningTranslate: 'Тень - это темная область, которую что-то создает, когда она блокирует солнце',
    wordTranslate: 'тень',
  },
  {
    id: '5e9f5ee35eb9e72bc21af744',
    group: 1,
    page: 3,
    word: 'supplement',
    image: 'files/04_0677.jpg',
    audio: 'files/04_0677.mp3',
    audioMeaning: 'files/04_0677_meaning.mp3',
    audioExample: 'files/04_0677_example.mp3',
    textMeaning: 'To <i>supplement</i> something is to add something else to it in a good way.',
    textExample: 'He <b>supplements</b> his diet with fresh fruits.',
    transcription: '[sʌ́pləmənt]',
    textExampleTranslate: 'Он дополняет свою диету свежими фруктами',
    textMeaningTranslate: 'Пополнить что-то - значит добавить что-то к этому хорошим способом',
    wordTranslate: 'дополнение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af743',
    group: 1,
    page: 3,
    word: 'strength',
    image: 'files/04_0676.jpg',
    audio: 'files/04_0676.mp3',
    audioMeaning: 'files/04_0676_meaning.mp3',
    audioExample: 'files/04_0676_example.mp3',
    textMeaning: '<i>Strength</i> is the ability to do hard work or exercise.',
    textExample: 'Eating good food builds up your <b>strength</b>.',
    transcription: '[streŋkθ]',
    textExampleTranslate: 'Еда хорошей пищи укрепляет ваши силы',
    textMeaningTranslate: 'Сила - это способность выполнять тяжелую работу или упражнения',
    wordTranslate: 'прочность',
  },
  {
    id: '5e9f5ee35eb9e72bc21af745',
    group: 1,
    page: 3,
    word: 'terror',
    image: 'files/04_0678.jpg',
    audio: 'files/04_0678.mp3',
    audioMeaning: 'files/04_0678_meaning.mp3',
    audioExample: 'files/04_0678_example.mp3',
    textMeaning: '<i>Terror</i> is a feeling of very strong fear.',
    textExample: 'I felt a sense of <b>terror</b> when the tiger chased me.',
    transcription: '[térəːr]',
    textExampleTranslate: 'Я чувствовал ужас, когда тигр преследовал меня',
    textMeaningTranslate: 'Террор - это чувство очень сильного страха',
    wordTranslate: 'террор',
  },
  {
    id: '5e9f5ee35eb9e72bc21af746',
    group: 1,
    page: 3,
    word: 'threat',
    image: 'files/04_0679.jpg',
    audio: 'files/04_0679.mp3',
    audioMeaning: 'files/04_0679_meaning.mp3',
    audioExample: 'files/04_0679_example.mp3',
    textMeaning: 'A <i>threat</i> is something bad that might happen.',
    textExample: 'Due to the dark clouds, there was a <b>threat</b> of a bad storm.',
    transcription: '[ɵret]',
    textExampleTranslate: 'Из-за темных облаков возникла угроза сильного шторма',
    textMeaningTranslate: 'Угроза - это нечто плохое, что может случиться',
    wordTranslate: 'угроза',
  },
  {
    id: '5e9f5ee35eb9e72bc21af747',
    group: 1,
    page: 3,
    word: 'victim',
    image: 'files/04_0680.jpg',
    audio: 'files/04_0680.mp3',
    audioMeaning: 'files/04_0680_meaning.mp3',
    audioExample: 'files/04_0680_example.mp3',
    textMeaning: 'A <i>victim</i> is a person who is hurt by a bad action.',
    textExample: 'I was a <b>victim</b> of a robbery.',
    transcription: '[víktim]',
    textExampleTranslate: 'Я был жертвой грабежа',
    textMeaningTranslate: 'Жертва - это человек, который пострадал от плохого поступка',
    wordTranslate: 'потерпевший',
  },
];
export default words;
